### ISSUE TITLE
Prepare UI for adding of user

### ISSUE THREAD

**Issue by anthonygacis** [bulan-devs/gov-inventory-front-end#4]
Needed UI components for user creation

* Personal Information
* Role
* Permission (based on condition)

**Comment by anthonygacis** [comment]
any update?

**Comment by DylanLee0918** [comment]
@anthonygacis 3 sir ma cclose kaso di pa in ppr ni jeph

**Comment by anthonygacis** [comment]
> 
> 
> @anthonygacis 3 sir ma cclose kaso di pa in ppr ni jeph

mao PR lang kamo
