### ISSUE TITLE
Add UI for notification

### ISSUE THREAD

**Issue by anthonygacis** [bulan-devs/gov-inventory-front-end#43]
Notification architecture
* Notification Title
* Notification Body
* Date
* Type (System, Transaction, Event)
      * choose some icon for every type (1 for system, 1 for transaction and 1 for event)
* Status (if read or unread) -> maybe an icon?

**Comment by DylanLee0918** [comment]
![Screenshot (355)](https://user-images.githubusercontent.com/56121820/116263198-c3228e00-a7ab-11eb-9d75-27b3abe0b408.png)

**Comment by anthonygacis** [comment]
mao goods na an sa read nan unread na status
siguro icon na lang na dot sa kaabay san title

**Comment by DylanLee0918** [comment]
diin sir an dot?

**Comment by anthonygacis** [comment]
sa right side lang san title
system (dot here) -> siguro kulang red
